name: Release Appimage
#concurrency:
  #group: build-${{ github.ref }}
  #cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: [ "trunk" ]
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  pull_request:
    branches: [ "trunk" ]
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:
  # Label of the container job
  build-appimage:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04-arm
          - ubuntu-24.04

    runs-on: ubuntu-latest
    env:
      VERSION: 0.27.0
      MINISIGN_KEY: RWTWLbO12+ig3lUExIor3xd6DdZaYFEozn8Bu8nIzY3ImuRYQszIQyyy
    steps:
    - uses: actions/checkout@v4

    - name: Build AppImage
      run: |
        export HOSTUID=$(id -u) HOSTGID=$(id -g)
        docker compose -f ./docker-compose.yml run --rm build

    - name: Create sha256sum
      run: |
        IMAGE_FILENAME=$(basename `find out/*AppImage`)
        echo "IMAGE_FILENAME=$IMAGE_FILENAME" >> $GITHUB_ENV
        cd out
        sha256sum "$IMAGE_FILENAME" > "$IMAGE_FILENAME.sha256sum"

    - name: Release AppImage
      if: ${{ github.ref == 'refs/heads/trunk' }}
      uses: ncipollo/release-action@v1
      with:
        name: 0ad-${{ env.VERSION }} AppImage
        allowUpdates: True
        prerelease: ${{ contains(env.VERSION, 'rc') }}
        artifacts: ./out/0ad*.AppImage*
        token: ${{ secrets.GITHUB_TOKEN }}
        omitNameDuringUpdate: True
        omitBodyDuringUpdate: True
        tag: v${{ env.VERSION }}
        replacesArtifacts: false
    - name: Upload Artifacts
      if: ${{ github.ref != 'refs/heads/trunk' }}
      uses: actions/upload-artifact@v4
      with:
        name: AppImage-${{ matrix.os }}
        path: ./out/0ad*.AppImage*
